let variableSinValor;
let variableValorNumerico = 1;
const miNombre = "Miguel Ángel";
const PI = 3.14;
const TAU = 2*PI;
const MiNumeroFav = 13.01;
let booleano1 = true;
let booleano2 = false;
let booleanoAnd = booleano1 && booleano2;
let booleanoOr = booleano1 || booleano2;
let booleanoNot = !booleano1;
let booleanoMix0 = (booleano1 || booleano2) && (booleano1 || (!booleano1 && !booleano2));
let booleanoMix1 = (booleano1 && TAU / 2 === PI) || (variableValorNumerico >= MiNumeroFav);
let booleanoMix2 = variableValorNumerico > 0 || variableValorNumerico < -(MiNumeroFav * TAU);
let valorSuma = MiNumeroFav + variableValorNumerico;
let valorResta = MiNumeroFav - variableValorNumerico;
let valorMultiplicacion = MiNumeroFav * variableValorNumerico;
let valorDivision = MiNumeroFav /  3;
let seisNoEsNueve = 6 != 9;
let incrementarDesp = 2;
let resultadoDesp = incrementarDesp++;
let incrementarAntes = 2;
let resultadoAntes = ++incrementarAntes;